[profile.default]
optimizer = true
optimizer-runs = 200
src = "src"
out = "out"
libs = ["lib"]
[lint]
lint_on_build = false



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
